=== schaefernanda/vinylCore/vinylCore.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="vinylCore" xmlns="vinylCore">

    <!-- VINYL (root) -->
    <xs:element name="vinyl" type="vinylWrapper"/>
        <xs:complexType name="vinylWrapper">
            <xs:sequence>
                <xs:element ref="album" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="recordingArtist" minOccurs="1" maxOccurs="unbounded"/>
                <xs:element ref="recordLabel" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="vinylProperties" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="trackList" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="accompanyingMaterial" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="acquisition" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="condition" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="monetaryValue" minOccurs="0" maxOccurs="unbounded"/>
                </xs:sequence>
        </xs:complexType>

        <!-- ALBUM -->
        <xs:element name="album">
            <xs:complexType>
                <xs:sequence>
                    <xs:element name="albumTitle" minOccurs="1" maxOccurs="1">
                        <xs:complexType>
                            <xs:attribute name="language" type="xs:language"/>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="albumSubtitle" minOccurs="0" maxOccurs="unbounded">
                        <xs:complexType>
                            <xs:attribute name="language" type="xs:language"/>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="albumAlternateTitle" minOccurs="0" maxOccurs="unbounded">
                        <xs:complexType>
                            <xs:attribute name="language" type="xs:language"/>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="albumIssue" minOccurs="0" maxOccurs="1">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:enumeration value="first press"/>
                                <xs:enumeration value="repress"/>
                                <xs:enumeration value="reissue"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                    <xs:element name="albumEdition" minOccurs="0" maxOccurs="unbounded">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:enumeration value="deluxe edition"/>
                                <xs:enumeration value="limited edition"/>
                                <xs:enumeration value="special edition"/>
                                <xs:enumeration value="club edition"/>
                                <xs:enumeration value="unofficial release"/>
                                <xs:enumeration value="remastered"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                    <xs:element name="catalogNumber" type="xs:string" minOccurs="1" maxOccurs="1"/>
                    <xs:element name="albumReleaseDate" type="xs:date" minOccurs="0" maxOccurs="1"/>
                    <xs:element name="albumYear" type="xs:gYear" minOccurs="0" maxOccurs="1"/>
                    <xs:element name="albumGenre" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
                    <xs:element name="albumCountryOfOrigin" type="xs:string" minOccurs="0" maxOccurs="1"/>
                    <xs:element name="albumCoverDescription" type="xs:string" minOccurs="0"
                        maxOccurs="1"/>
                    <xs:element name="boxSetAffiliation" type="xs:string" minOccurs="0" maxOccurs="1"/>
                    <xs:element name="albumNote" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                </xs:sequence>
            </xs:complexType>
        </xs:element>

        <!-- RECORDING ARTIST -->
        <xs:element name="recordingArtist">
            <xs:complexType>
                <xs:sequence>
                    <xs:element name="recordingArtistName" type="xs:string" minOccurs="1" maxOccurs="1"/>
                    <xs:element name="recordingArtistAlternateName" type="xs:string" minOccurs="0"
                        maxOccurs="unbounded"/>
                    <xs:element name="recordingArtistNationality" type="xs:string" minOccurs="0"
                        maxOccurs="unbounded"/>
                    <xs:element name="recordingArtistNote" type="xs:string" minOccurs="0"
                        maxOccurs="unbounded"/>
                </xs:sequence>
            </xs:complexType>
        </xs:element>

        <!-- RECORD LABEL -->
        <xs:element name="recordLabel">
            <xs:complexType>
                <xs:sequence>
                    <xs:element name="recordLabelName" minOccurs="0" maxOccurs="1">
                        <xs:complexType>
                            <xs:attribute name="language" type="xs:language"/>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="recordLabelAddress" type="xs:string" minOccurs="0" maxOccurs="1"/>
                    <xs:element name="recordLabelWebsite" type="xs:string" minOccurs="0"
                        maxOccurs="unbounded"/>
                    <xs:element name="recordLabelDescription" type="xs:string" minOccurs="0"
                        maxOccurs="1"/>
                </xs:sequence>
            </xs:complexType>
        </xs:element>

        <!-- VINYL PROPERTIES -->
        <xs:element name="vinylProperties">
            <xs:complexType>
                <xs:sequence>
                    <xs:element name="vinylSize" minOccurs="1" maxOccurs="1">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:enumeration value="16 in"/>
                                <xs:enumeration value="12 in"/>
                                <xs:enumeration value="11 in"/>
                                <xs:enumeration value="10 in"/>
                                <xs:enumeration value="9 in"/>
                                <xs:enumeration value="8 in"/>
                                <xs:enumeration value="7 in"/>
                                <xs:enumeration value="6 ½ in"/>
                                <xs:enumeration value="6 in"/>
                                <xs:enumeration value="5 ½ in"/>
                                <xs:enumeration value="5 in"/>
                                <xs:enumeration value="4 in"/>
                                <xs:enumeration value="3 in"/>
                                <xs:enumeration value="2 in"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                    <xs:element name="vinylColor" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
                    <xs:element name="vinylSpeed" minOccurs="1" maxOccurs="1">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:enumeration value="8 ⅓ RPM"/>
                                <xs:enumeration value="16 ⅔ RPM"/>
                                <xs:enumeration value="33 ⅓ RPM"/>
                                <xs:enumeration value="45 RPM"/>
                                <xs:enumeration value="78 RPM"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                    <xs:element name="soundChannelType" minOccurs="0" maxOccurs="1">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:enumeration value="stereo"/>
                                <xs:enumeration value="mono"/>
                                <xs:enumeration value="quadraphonic"/>
                                <xs:enumeration value="ambisonic"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                </xs:sequence>
            </xs:complexType>
        </xs:element>

        <!-- TRACK LIST -->
        <xs:element name="trackList">
            <xs:complexType>
                <xs:sequence>
                    <xs:element name="trackTitle" minOccurs="1" maxOccurs="unbounded">
                        <xs:complexType>
                            <xs:attribute name="discNumber" type="xs:float"/>
                            <xs:attribute name="vinylSide">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="a"/>
                                        <xs:enumeration value="b"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:attribute>
                            <xs:attribute name="trackPosition" type="xs:float"/>
                            <xs:attribute name="language" type="xs:language"/>
                            <xs:attribute name="trackDuration" type="xs:duration"/>
                        </xs:complexType>
                    </xs:element>
                </xs:sequence>
            </xs:complexType>
        </xs:element>

        <!-- ACCOMPANYING MATERIAL -->
        <xs:element name="accompanyingMaterial">
            <xs:complexType>
            <xs:sequence>
                <xs:element name="accompanyingMaterialType" type="xs:string" minOccurs="1"
                    maxOccurs="1"/>
                <xs:element name="accompanyingMaterialDescription" type="xs:string" minOccurs="0"
                    maxOccurs="1"/>
            </xs:sequence>
            </xs:complexType>
        </xs:element>

        <!-- ACQUISITION -->
        <xs:element name="acquisition">
            <xs:complexType>
                <xs:sequence>
                    <xs:element name="acquisitionDate" type="xs:date" minOccurs="0" maxOccurs="1"/>
                    <xs:element name="acquiredFrom" minOccurs="1" maxOccurs="unbounded">
                        <xs:complexType>
                            <xs:attribute name="acquiredFromType">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="person"/>
                                        <xs:enumeration value="marketplace"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:attribute>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="purchasePrice" minOccurs="0" maxOccurs="1">
                        <xs:complexType>
                            <xs:simpleContent>
                                <xs:extension base="xs:string">
                                    <xs:attribute name="currency" type="xs:string"/>
                                </xs:extension>
                            </xs:simpleContent>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="acquisitionNote" type="xs:string" minOccurs="0" maxOccurs="1"/>
                </xs:sequence>
            </xs:complexType>
        </xs:element>

        <!-- CONDITION -->
        <xs:element name="condition">
            <xs:complexType>
                <xs:sequence>
                    <xs:element name="vinylCondition" minOccurs="1" maxOccurs="unbounded">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="discCondition" minOccurs="0" maxOccurs="1">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:string">
                                            <xs:enumeration value="mint"/>
                                            <xs:enumeration value="near-mint"/>
                                            <xs:enumeration value="very good plus"/>
                                            <xs:enumeration value="very good"/>
                                            <xs:enumeration value="good plus"/>
                                            <xs:enumeration value="fair"/>
                                            <xs:enumeration value="poor"/>
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:element>
                                <xs:element name="discConditionNote" type="xs:string" minOccurs="0"
                                    maxOccurs="1"/>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="packagingCondition" minOccurs="0" maxOccurs="1">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="jacketCondition" minOccurs="0" maxOccurs="1">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:string">
                                            <xs:enumeration value="mint"/>
                                            <xs:enumeration value="near-mint"/>
                                            <xs:enumeration value="very good plus"/>
                                            <xs:enumeration value="very good"/>
                                            <xs:enumeration value="good plus"/>
                                            <xs:enumeration value="fair"/>
                                            <xs:enumeration value="poor"/>
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:element>
                                <xs:element name="jacketConditionNote" type="xs:string" minOccurs="0"
                                    maxOccurs="1"/>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                </xs:sequence>
            </xs:complexType>
        </xs:element>

        <!-- MONETARY VALUE -->
        <xs:element name="monetaryValue">
            <xs:complexType>
                <xs:sequence>
                    <xs:element name="valueAssessed" minOccurs="0" maxOccurs="1">
                        <xs:complexType>
                            <xs:simpleContent>
                                <xs:extension base="xs:string">
                                    <xs:attribute name="currency" type="xs:string"/>
                                </xs:extension>
                            </xs:simpleContent>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="dateOfAssessment" type="xs:date" minOccurs="0" maxOccurs="1"/>
                    <xs:element name="sourceOfAssessment" type="xs:string" minOccurs="0" maxOccurs="1"/>
                </xs:sequence>
            </xs:complexType>
        </xs:element>

</xs:schema>

=== schaefernanda/vinylCore/vinylCore_TheAstrudGilbertoAlbum.xml
<?xml version="1.0" encoding="UTF-8"?>
<vinylCore:vinyl xmlns:vinylCore="vinylCore"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="vinylCore http://mschafr2.web.illinois.edu/vinylCore.xsd">
    <vinylCore:album>
        <vinylCore:albumTitle language="en-US">The Astrud Gilberto Album</vinylCore:albumTitle>
        <vinylCore:albumIssue>reissue</vinylCore:albumIssue>
        <vinylCore:catalogNumber>V6-8608</vinylCore:catalogNumber>
        <vinylCore:albumReleaseDate>2011-10-01</vinylCore:albumReleaseDate>
        <vinylCore:albumYear>2011</vinylCore:albumYear>
        <vinylCore:albumGenre>bossa nova</vinylCore:albumGenre>
        <vinylCore:albumCountryOfOrigin>United States</vinylCore:albumCountryOfOrigin>
    </vinylCore:album>
    <vinylCore:recordingArtist>
        <vinylCore:recordingArtistName>Astrud Gilberto</vinylCore:recordingArtistName>
        <vinylCore:recordingArtistNationality>Brazil</vinylCore:recordingArtistNationality>
        <vinylCore:recordingArtistNote>From 1959-1964, Astrud Gilberto was married to Brazilian singer João Gilberto, a pioneer of bossa nova.</vinylCore:recordingArtistNote>
    </vinylCore:recordingArtist>
    <vinylCore:recordLabel>
        <vinylCore:recordLabelName language="en-US">The Verve Music Group</vinylCore:recordLabelName>
        <vinylCore:recordLabelDescription>This album was recorded at RCA Studios but was licensed by Metro-Goldwyn-Mayer, Inc. (Verve Series).</vinylCore:recordLabelDescription>
    </vinylCore:recordLabel>
    <vinylCore:vinylProperties>
        <vinylCore:vinylSize>12 in</vinylCore:vinylSize>
        <vinylCore:vinylColor>black</vinylCore:vinylColor>
        <vinylCore:vinylSpeed>33 ⅓ RPM</vinylCore:vinylSpeed>
        <vinylCore:soundChannelType>stereo</vinylCore:soundChannelType>
    </vinylCore:vinylProperties>
    <vinylCore:trackList>
        <vinylCore:trackTitle discNumber="1" vinylSide="a" trackPosition="1" language="en-US" trackDuration="00:02:10">Once I Loved</vinylCore:trackTitle>
        <vinylCore:trackTitle discNumber="1" vinylSide="a" trackPosition="2" language="pt-BR" trackDuration="00:02:18">Água De Beber</vinylCore:trackTitle>
        <vinylCore:trackTitle discNumber="1" vinylSide="a" trackPosition="3" language="en-US" trackDuration="00:02:39">Meditation</vinylCore:trackTitle>
        <vinylCore:trackTitle discNumber="1" vinylSide="a" trackPosition="4" language="en-US" trackDuration="00:02:30">And Roses And Roses</vinylCore:trackTitle>
        <vinylCore:trackTitle discNumber="1" vinylSide="a" trackPosition="5" language="pt-BR" trackDuration="00:02:55">O Morro Não Tem Vez</vinylCore:trackTitle>
        <vinylCore:trackTitle discNumber="1" vinylSide="a" trackPosition="6" language="en-US" trackDuration="00:02:45">How Insensitive</vinylCore:trackTitle>
        <vinylCore:trackTitle discNumber="1" vinylSide="b" trackPosition="1" language="pt-BR" trackDuration="00:02:45">Dindi</vinylCore:trackTitle>
        <vinylCore:trackTitle discNumber="1" vinylSide="b" trackPosition="2" language="en-US" trackDuration="00:02:12">Photograph</vinylCore:trackTitle>
        <vinylCore:trackTitle discNumber="1" vinylSide="b" trackPosition="3" language="en-US" trackDuration="00:02:00">Dreamer</vinylCore:trackTitle>
        <vinylCore:trackTitle discNumber="1" vinylSide="b" trackPosition="4" language="pt-BR" trackDuration="00:02:15">Só Tinha De Ser Com Você</vinylCore:trackTitle>
        <vinylCore:trackTitle discNumber="1" vinylSide="b" trackPosition="5" language="en-US" trackDuration="00:03:09">All That's Left Is To Say Goodbye</vinylCore:trackTitle>
    </vinylCore:trackList>
    <vinylCore:acquisition>
        <vinylCore:acquiredFrom acquiredFromType="marketplace">Amoeba Music</vinylCore:acquiredFrom>
        <vinylCore:purchasePrice currency="US dollar">$29.98</vinylCore:purchasePrice>
        <vinylCore:acquisitionNote>This album was purchased at the original Amoeba Music location in Los Angeles, California, in the summer of 2019.</vinylCore:acquisitionNote>
    </vinylCore:acquisition>
    <vinylCore:condition>
        <vinylCore:vinylCondition>
            <vinylCore:discCondition>mint</vinylCore:discCondition>
        </vinylCore:vinylCondition>
        <vinylCore:packagingCondition>
            <vinylCore:jacketCondition>mint</vinylCore:jacketCondition>
        </vinylCore:packagingCondition>
    </vinylCore:condition>
</vinylCore:vinyl>

=== schaefernanda/vinylCore/sample_records/vinylCore_PetSounds.xml
<?xml version="1.0" encoding="UTF-8"?>
<vinylCore:vinyl xmlns:vinylCore="vinylCore"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="vinylCore http://mschafr2.web.illinois.edu/vinylCore.xsd">
    <vinylCore:album>
        <vinylCore:albumTitle language="en-US">Pet Sounds</vinylCore:albumTitle>
        <vinylCore:albumIssue>reissue</vinylCore:albumIssue>
        <vinylCore:albumEdition>deluxe edition</vinylCore:albumEdition>
        <vinylCore:catalogNumber>ST 2458</vinylCore:catalogNumber>
        <vinylCore:albumReleaseDate>2016-06-10</vinylCore:albumReleaseDate>
        <vinylCore:albumYear>2016</vinylCore:albumYear>
        <vinylCore:albumGenre>psychedelic pop</vinylCore:albumGenre>
        <vinylCore:albumCountryOfOrigin>United States</vinylCore:albumCountryOfOrigin>
        <vinylCore:albumCoverDescription>The album cover has the classic image of the Beach Boys feeding goats. This cover is the same as the original edition.</vinylCore:albumCoverDescription>
        <vinylCore:albumNote>This is the 50th Anniversary Edition.</vinylCore:albumNote>
    </vinylCore:album>
    <vinylCore:recordingArtist>
        <vinylCore:recordingArtistName>The Beach Boys</vinylCore:recordingArtistName>
    </vinylCore:recordingArtist>
    <vinylCore:recordLabel>
        <vinylCore:recordLabelName language="en-US">Capitol Records</vinylCore:recordLabelName>
        <vinylCore:recordLabelAddress>1750 N. Vine Street, Hollywood, CA 90028 - U.S.A.</vinylCore:recordLabelAddress>
    </vinylCore:recordLabel>
    <vinylCore:vinylProperties>
        <vinylCore:vinylSize>12 in</vinylCore:vinylSize>
        <vinylCore:vinylColor>black</vinylCore:vinylColor>
        <vinylCore:vinylSpeed>33 â…“ RPM</vinylCore:vinylSpeed>
        <vinylCore:soundChannelType>stereo</vinylCore:soundChannelType>
    </vinylCore:vinylProperties>
    <vinylCore:trackList>
        <vinylCore:trackTitle discNumber="1" vinylSide="a" trackPosition="1" language="en-US" trackDuration="00:02:22">Wouldn't It Be Nice</vinylCore:trackTitle>
        <vinylCore:trackTitle discNumber="1" vinylSide="a" trackPosition="2" language="en-US" trackDuration="00:02:33">You Still Believe In Me</vinylCore:trackTitle>
        <vinylCore:trackTitle discNumber="1" vinylSide="a" trackPosition="3" language="en-US" trackDuration="00:02:27">That's Not Me</vinylCore:trackTitle>
        <vinylCore:trackTitle discNumber="1" vinylSide="a" trackPosition="4" language="en-US" trackDuration="00:02:52">Don't Talk (Put Your Head On My Shoulder)</vinylCore:trackTitle>
        <vinylCore:trackTitle discNumber="1" vinylSide="a" trackPosition="5" language="en-US" trackDuration="00:03:01">I'm Waiting For The Day</vinylCore:trackTitle>
        <vinylCore:trackTitle discNumber="1" vinylSide="a" trackPosition="6" language="en-US" trackDuration="00:02:18">Let's Go Away For Awhile</vinylCore:trackTitle>
        <vinylCore:trackTitle discNumber="1" vinylSide="a" trackPosition="7" language="en-US" trackDuration="00:02:57">Sloop John B</vinylCore:trackTitle>
        <vinylCore:trackTitle discNumber="1" vinylSide="b" trackPosition="1" language="en-US" trackDuration="00:02:46">God Only Knows</vinylCore:trackTitle>
        <vinylCore:trackTitle discNumber="1" vinylSide="b" trackPosition="2" language="en-US" trackDuration="00:03:10">I Know There's An Answer</vinylCore:trackTitle>
        <vinylCore:trackTitle discNumber="1" vinylSide="b" trackPosition="3" language="en-US" trackDuration="00:02:38">Here Today</vinylCore:trackTitle>
        <vinylCore:trackTitle discNumber="1" vinylSide="b" trackPosition="4" language="en-US" trackDuration="00:03:21">I Just Wasn't Made For These Times</vinylCore:trackTitle>
        <vinylCore:trackTitle discNumber="1" vinylSide="b" trackPosition="5" language="en-US" trackDuration="00:02:20">Pet Sounds</vinylCore:trackTitle>
        <vinylCore:trackTitle discNumber="1" vinylSide="b" trackPosition="6" language="en-US" trackDuration="00:02:16">Caroline, No</vinylCore:trackTitle>
    </vinylCore:trackList>
    <vinylCore:acquisition>
        <vinylCore:acquisitionDate>2019-08-10</vinylCore:acquisitionDate>
        <vinylCore:acquiredFrom acquiredFromType="marketplace">Amoeba Music</vinylCore:acquiredFrom>
        <vinylCore:purchasePrice currency="US dollar">$24.98</vinylCore:purchasePrice>
        <vinylCore:acquisitionNote>This album was purchased at the original Amoeba Music location in Los Angeles, California.</vinylCore:acquisitionNote>
    </vinylCore:acquisition>
    <vinylCore:condition>
        <vinylCore:vinylCondition>
            <vinylCore:discCondition>near-mint</vinylCore:discCondition>
            <vinylCore:discConditionNote>The disc is in mint condition, but the label is in near-mint condition because it is a little ripped.</vinylCore:discConditionNote>
        </vinylCore:vinylCondition>
        <vinylCore:packagingCondition>
            <vinylCore:jacketCondition>mint</vinylCore:jacketCondition>
        </vinylCore:packagingCondition>
    </vinylCore:condition>
</vinylCore:vinyl>
